# File names are either absolute or relative to the parent folder of the vhdl_ls.toml file
[libraries]

work.files = [
  'lib/*.vhd',
  'src/*/*.vhd',
  'test/*/*.vhd',
]

# Libraries can be marked as third-party to disable some analysis warnings, such as unused declarations
#UNISIM.files = [
#  'C:\Xilinx\Vivado\2023.1\data\vhdl\src\unisims\unisim_VCOMP.vhd',
#]
#UNISIM.is_third_party = true